INSERT INTO PRODUCT (ID, NAME, PRICE, PRODUCT_TYPE, VISIBLE_TO_SELL) VALUES (default, 'Huawei', 700.00, 'SMARTPHONE', true);
INSERT INTO PRODUCT (ID, NAME, PRICE, PRODUCT_TYPE, VISIBLE_TO_SELL) VALUES (default, 'iPhone', 999.99, 'SMARTPHONE', false);
